### PR TITLE
Latest updates

### PR DESCRIPTION
**Pull request by techcoderx**
* Replaced every instance of `text-davinci-003` with `gpt-3.5-turbo`. Everything else is still working correctly.
* Fixed thread summarization
* Cherry-picked commit from #15, added pm2 stop command
* Updated replit-setup.sh script

### CODE REVIEW

**Comment by firtoz** [comment]
🤔 neat, will give it a try hopefully in a few days and let you know how it goes!

**Comment by firtoz** [comment]
BTW Does canvas work with replit now? Have you tried running this branch on replit?

**Comment by techcoderx** [comment]
Not sure about canvas as I've never used it, seems that it only received two minor updates. Other than that I ran the branch on replit and it works (at least for me), though canvas must be installed or else yarn build will fail.

**Comment by techcoderx** [comment]
Looks like I got that one working as well

Screenshot 2023-06-11 at 6 18 01 PM

**Comment by firtoz** [comment]
Nice!

**Comment by firtoz** [comment]
Update: I'll be able to review it in the week sometime 🙏

**Comment by firtoz** [comment]
@techcoderx LGTM! How would you like the payment? :D

**Comment by techcoderx** [comment]
Would prefer to use it towards future Erin invoices

**Comment by firtoz** [comment]
> Would prefer to use it towards future Erin invoices

Understood, will send you a DM in Discord 👍

**Pull request merged**
